name: Deploy Angular App

on:
  push:
    branches: [ main ]
  
  jobs:
    build-angular:
      runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install Angular dependencies
        run: npm install

      - name: Build Angular app
        run: ng build

      - name: Upload Angular files
        uses: actions/upload-artifact@v3
        with:
          name: angular-app
          path: dist

     deploy-angular:
    needs: [ build-angular ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Angular files
        uses: actions/download-artifact@v3
        with:
          name: angular-app
          path: dist

      - name: Deploy Angular app to S3 (replace with your S3 bucket and deployment path)
        run: |
          aws s3 cp --recursive dist s3://your-bucket-name/your-deployment-path
          echo "Angular app deployed to S3!"